---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: mtail:3.0.0-rc50
        args:
        - "--logtostderr"
        - "--logs"
        - "/var/log/*.log"
        - "--logs"
        - "/var/log/containers/*.log"
        - "--port"
        - "3903"
        - "--progs"
        - "/etc/mtail"
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - name: metrics
          containerPort: 3903
          hostPort: 3903
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/mtail
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/master
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-configmap
