---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  podMetricsEndpoints:
  - port: "metrics"
    path: "/metrics"
